### ISSUE TITLE
Check Statusページが機能していない

### ISSUE THREAD

**Issue by TetsuOtter** [GCXHam/dev-daemon#21]
自身の名前が表示されず、またチームメンバーも表示されていない状態になっている。

状態の共有も機能していないため、機能実装を行う必要がある。

**Comment by TetsuOtter** [comment]
> 2つのタスクと捉えて

それに加えて, CheckStatusページでハードコートされたダミーデータが表示されてる状態なので, その表示をうまいことDBと連携させるタスクもありますので, 合計3つに分解できそうです

実装の方法についてはその通りで大丈夫だと思います

**Comment by Yuki992411** [comment]
そしたら、タスクを3つにわけようと思います！
