### ISSUE TITLE
ログイン時のdbとの連携を行なう

### ISSUE THREAD

**Issue by Yuki992411** [GCXHam/dev-daemon#23]
`Login.js`の`signInWithEmailAndPassword`に`DevDaemonDBController`ハンドラーを用いてdbの操作を行なう機能を実装する

**Comment by Yuki992411** [comment]
@TetsuOtter 

色々あって，少々時間が空いてしまいましたが，本年も宜しくお願いします😁

さて，`Login.tsx`にて，該当するteam名を探す処理を書くことになると思いますが，これは，
`DevDaemonDBController`の`addMemberToTeam`を使用する形で合ってますか？

もし，その場合，新規のチームIDが引数で渡された場合，L.466あたりの
```ts
if (!(await this.isTeamIDAlreadyExists(team_id))) {
      throw new Error("TeamID was not found in the DB");
    }
```
のようにエラーを返すより，新規チームを作成する処理の方がよいかもしれませんがどうですか
（それかホップアップで確認メッセージを表示させてから新規チーム作成とか）？

**Comment by TetsuOtter** [comment]
こちらこそ, 今年もよろしくお願いします!

該当するteam名を探す処理については, ユーザデータに「ユーザが所属するチーム」が保存される予定なので, そこから参照する予定です.  使用する関数は`getJoiningTeamList`の予定です.
https://github.com/GCXHam/dev-daemon/blob/ef922265821dc7d2ba7ada3c350ec898ffb0444c/src/DevDaemonDBController.ts#L311-L330

`addMemberToTeam`は, 既存チームに対して新規にメンバーを登録する関数なので, チームIDが存在しない場合はチームIDのtypoが考えられるため, エラーを返す処理にしています.

ログイン画面から新規チーム作成を行う場合には, UI側でチームIDが存在しないというエラーを表示した上で, ユーザに新規チーム作成の確認を求めるフローを想定しています.  なお, 新規チーム作成に使用するのは`createNewTeam`関数の予定です.
https://github.com/GCXHam/dev-daemon/blob/ef922265821dc7d2ba7ada3c350ec898ffb0444c/src/DevDaemonDBController.ts#L356-L380
