### ISSUE TITLE
srcフォルダがごちゃごちゃしている

### ISSUE THREAD

**Issue by TetsuOtter** [GCXHam/dev-daemon#31]
srcフォルダ内に, いわゆる「ページ」と「コンポーネント」と… みたいに混在していて, わかりづらい.

- src/
  - component/
    - Badge.css
    - Badge.js
    - Button.css
    - Button.js
    - FormBox.css
    - FormBox.js
  - page/
    - App.js
    - App.test.js
    - CheckStatus.css
    - CheckStatus.js
    - index.css
    - index.js
    - Login.css
    - Login.js
    - SignUp.css
    - SignUp.js
  - AuthContext.js
  - DevDaemonDBController.ts
  - FirebaseConfig.js

みたいな感じで分けてあげたい.

本当はcssとかcontextとかも別フォルダに分離した方がわかりやすいけど, この数/規模でそこまで分離せずとも…と思うので, これについては要検討ということで

**Comment by Yuki992411** [comment]
確かに、そろそろ分割した方がよさそうですね。。
上記の分割でよいと思います。
あとは、`__TEST__/`を`src/`に配置し、`App.test.js`含めテストコードをまとめても良いと思います。
