### ISSUE TITLE
ほぼすべてのファイルをTypeScriptにしたい

### ISSUE THREAD

**Issue by TetsuOtter** [GCXHam/dev-daemon#33]
型制約がないと「そこに何があるのか, また本当にそこにあるのか」がわからず, 非常に不安になる

ほか, VSCodeでの開発中に入力補完が効かないのがつらいため, ほぼすべてのコードをTypeScript化したい

**Comment by Yuki992411** [comment]
分かりました！
少々大規模になると思いますが、一旦PRをお願い致します🙇‍♂️

Issue を分割されても大丈夫です。

**Comment by TetsuOtter** [comment]
はい.  #26 をやるのに入力補完が効かないのがつらかったので, いま修正を試行してます

TS化が完了し次第PRを立てます！
